spring:
  application:
    name: tracekit-kotlin-demo

server:
  port: 8082

tracekit:
  enabled: true
  api-key: ctxio_c16d0728ea99bbd5b849c6341e49dff99263018a19992faafe815e76b01dee97
  service-name: kotlin-sdk
  environment: development
  endpoint: http://localhost:8081/v1/traces
  enable-code-monitoring: true
  local-ui-port: 9999

logging:
  level:
    root: INFO
    dev.tracekit: DEBUG
    org.springframework.web: INFO
